### ISSUE TITLE
2 Players on 1 Llama?

### ISSUE THREAD

**Issue by squishycat92** [justinhschaaf/LlamaSteeds#1]
Hello, I think this mod is great! If possible, could you add the functionality for 2 players to ride on one llama? Thank you so much!

**Comment by justinhschaaf** [comment]
Hello! I'm glad you enjoy the mod. I won't be implementing the ability for 2 players to ride on one llama, as I think it would be too complex for me to do through exclusively mixins (as this mod is designed to be as simple as possible--note the same mod version working for 1.14+ on Fabric); however, an alternative solution could be having one player on a saddled llama leading a second llama with a player on it (though I think the second llama would have to be unsaddled, as the player control would probably override caravan behavior). 

Thank you for the feedback, have a great day! 🙂
