### ISSUE TITLE
Feature Suggestion

### ISSUE THREAD

**Issue by awesomedeity** [justinhschaaf/LlamaSteeds#4]
I was wondering if it was possible to send the caravan signal to other llamas when you're mounted? Would make the caravan feature a lot more fun to use if they'd follow a mounted llama instead of having to require a lead.

**Comment by justinhschaaf** [comment]
I really like your idea, and I think it might be possible without overcomplicating or breaking things, I'd just need to do some digging and figure out exactly how the caravan signaling works. I'll try to get to it sometime this week, as I've been in a programming mood lately, and I really wanna see this work as it fits the goals of the mod so well. I'll keep you updated.

**Comment by justinhschaaf** [comment]
Looking through the game code today, I thought I was going to have to reimplement a lot of what Mojang had wrote until I realized I could replace every instance where the caravan checks if the llama is leashed to also check if the llama has a player with a saddle on it. It's simple, it's stupid, it works. 

Just published it in the new Fabric version on GitHub Releases, and it should be approved on CurseForge in about a day or so. I'll try to port it to Forge tonight and release that too before closing this.

Thank you so much for contributing the idea, and thanks for enjoying the mod. Have a great day! :slightly_smiling_face:

**Comment by awesomedeity** [comment]
You're awesome!! I'm glad it was simple to implement and I'm looking forward to the update.
