### ISSUE TITLE
Please Update to 1.20.2 

### ISSUE THREAD

**Issue by sternschnaube** [justinhschaaf/LlamaSteeds#5]
https://pastebin.com/raw/qtSMRa7N

**Comment by justinhschaaf** [comment]
Should be completed with https://github.com/justinhschaaf/LlamaSteeds/commit/509b3dc276bee5201fd2733c8523ab451d708eca and https://github.com/justinhschaaf/LlamaSteeds/commit/8d7cddc6ceca3e6fc11297f122bc76cb0eaf0a67, sorry for the delay in getting this done! New release is already out on GitHub releases and Modrinth, usually takes a day or two to get approved on Curseforge. Feel free to let me know if you're still running into issues, thank you for enjoying Llama Steeds!

**Comment by venaminecraft** [comment]
Thank you 🥳🥳
